# Generated by Django 4.2.1 on 2023-05-27 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_options_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "postagem",
                "verbose_name_plural": "postagens",
            },
        ),
    ]
