# Generated by Django 4.2.1 on 2023-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="post_images/"),
        ),
    ]
